### ISSUE TITLE
smelter

### ISSUE THREAD

**Issue by albator84** [sor1n/Jewelrycraft#11]
The iron gravel ore of Tinkers Construct become a ingot of tin of forestry when I smelt iron gravel and I cast to ingot.

**Comment by sor1n** [comment]
That is indeed a weird bug. Unfortunately idk if I can fix it. Ores will always be weird as you can't get what ingot it ends up as easily. So the way I do it might create an issue such as this. Although it is a problem, I will make sure to try to fix it. No promises though.

**Comment by sor1n** [comment]
Issue has been fixed in version 1.0.8 :)
