### ISSUE TITLE
complete  game crash after using the ritual and get the Midas Touch. for now no way to start the save again.

### ISSUE THREAD

**Issue by ghost** [sor1n/Jewelrycraft#12]
i have builded the ritual structure and have placed a golden ring in the middle pedestal.
after that i placed a enderium nugget in one of the other pedestals.
then i clicked to the eye ind the middle of the structure
the midas touch appears in the left upper corner of the screen and all the stuff i touched turned in to gold.
So i throw all the golden stuff in a chest. thinking no golden stuff in the inventory no effect.
as i moved to the next item in my hotbar the game stops imediatly and goes to the startscreen.
i shut down the hole game and tried to start again but i cant`t start the world.
it is possible to start a new world and other world but not the crashed one.
i don`t know if this is an error, bug or something other this should be an information

have saved the log in a file http://paste.ee/p/faSl1

if i do something wrong please tell me.
greetings jokish

**Comment by sor1n** [comment]
Can you provide a crash log? Also, could you tell me what version of the mod are you using and do you remember what item did you hover over before you crashed?

**Comment by sor1n** [comment]
If you are able to answer my questions, please do.

**Comment by sor1n** [comment]
Nobody said anything, so I will just assume I have fixed it and you just forgot to tell me that
