### ISSUE TITLE
Compilation fails without CurseForge API Key

### ISSUE THREAD

**Issue by Laikulo** [sor1n/Jewelrycraft#16]
Code that uses that should check that it exists first, Buildscript does not compile without it.

See Here http://ci.jam-craft.net/job/JewelryCraft/branch/1.7.10/43/console

**Comment by sor1n** [comment]
Yes KJ, I am aware of the multiple build fails XD Unfortunately I have no solution for the problem, really.

**Comment by sor1n** [comment]
Well this is fixed, thank you for your help ^^
