### ISSUE TITLE
Crash on liquids 

### ISSUE THREAD

**Issue by LiSirNo** [sor1n/Jewelrycraft#18]
Hello there is crash note after using liquids "page" in equipment when on creative mode 

---- Minecraft Crash Report ----
// This is a token for 1 free hug. Redeem at your nearest Mojangsta: [~~HUG~~]

Time: 27.05.15 18:40
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
    at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:427)
    at darkknight.jewelrycraft.item.ItemMoltenMetalBucket.func_77653_i(ItemMoltenMetalBucket.java:222)
    at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:427)
    at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:489)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.updateFilteredItems(GuiContainerCreative.java:378)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147053_i(GuiContainerCreative.java:335)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147050_b(GuiContainerCreative.java:550)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146286_b(GuiContainerCreative.java:456)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146274_d(GuiContainerCreative.java:566)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1628)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:961)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:887)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- Head --
Stacktrace:
    at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:427)
    at darkknight.jewelrycraft.item.ItemMoltenMetalBucket.func_77653_i(ItemMoltenMetalBucket.java:222)
    at net.minecraft.item.ItemStack.func_82833_r(ItemStack.java:427)
    at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:489)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.updateFilteredItems(GuiContainerCreative.java:378)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147053_i(GuiContainerCreative.java:335)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147050_b(GuiContainerCreative.java:550)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146286_b(GuiContainerCreative.java:456)
    at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306)
    at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
    at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146274_d(GuiContainerCreative.java:566)
    at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)

-- Affected screen --
Details:
    Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative

-- Affected level --
Details:
    Level name: MpServer
    All players: 1 total; [EntityClientPlayerMP['as'/318, l='MpServer', x=-327,87, y=5,62, z=-12,90]]
    Chunk stats: MultiplayerChunkCache: 289, 289
    Level seed: 0
    Level generator: ID 01 - flat, ver 0. Features enabled: false
    Level generator options: 
    Level spawn location: World: (-390,4,-48), Chunk: (at 10,0,0 in -25,-3; contains blocks -400,0,-48 to -385,255,-33), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
    Level time: 55515 game time, 42050 day time
    Level dimension: 0
    Level storage version: 0x00000 - Unknown?
    Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
    Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
    Forced entities: 72 total; [EntityChicken['Chicken'/256, l='MpServer', x=-286,41, y=4,00, z=29,53], EntityChicken['Chicken'/257, l='MpServer', x=-273,88, y=4,00, z=39,03], EntityChicken['Chicken'/258, l='MpServer', x=-282,44, y=4,00, z=33,59], EntitySheep['Sheep'/259, l='MpServer', x=-281,28, y=4,00, z=39,28], EntitySheep['Sheep'/265, l='MpServer', x=-274,53, y=4,00, z=32,75], EntityChicken['Chicken'/267, l='MpServer', x=-283,47, y=4,00, z=51,47], EntitySheep['Sheep'/268, l='MpServer', x=-291,91, y=4,00, z=43,84], EntityChicken['Chicken'/269, l='MpServer', x=-282,47, y=4,00, z=54,31], EntitySheep['Sheep'/270, l='MpServer', x=-284,16, y=4,00, z=68,81], EntityItem['item.item.egg'/1197056, l='MpServer', x=-264,34, y=4,13, z=44,84], EntitySpider['Spider'/1272327, l='MpServer', x=-275,38, y=4,00, z=67,16], EntityCow['Cow'/282, l='MpServer', x=-251,47, y=4,00, z=-52,19], EntitySheep['Sheep'/283, l='MpServer', x=-269,16, y=4,00, z=-45,41], EntityClientPlayerMP['as'/318, l='MpServer', x=-327,87, y=5,62, z=-12,90], EntitySheep['Sheep'/284, l='MpServer', x=-263,38, y=4,00, z=-31,78], EntityCow['Cow'/285, l='MpServer', x=-256,13, y=4,00, z=-24,97], EntityCow['Cow'/286, l='MpServer', x=-260,66, y=4,00, z=-26,28], EntityCow['Cow'/287, l='MpServer', x=-263,91, y=4,00, z=-10,03], EntityItem['item.item.feather'/730644, l='MpServer', x=-274,16, y=4,13, z=37,44], EntitySheep['Sheep'/288, l='MpServer', x=-271,75, y=4,00, z=10,22], EntityPig['Pig'/289, l='MpServer', x=-266,72, y=4,00, z=24,50], EntityChicken['Chicken'/290, l='MpServer', x=-269,09, y=4,00, z=41,41], EntityItem['item.item.egg'/1235760, l='MpServer', x=-267,69, y=4,13, z=41,81], EntityChicken['Chicken'/291, l='MpServer', x=-263,63, y=4,00, z=47,84], EntityChicken['Chicken'/292, l='MpServer', x=-264,84, y=4,00, z=47,03], EntityPig['Pig'/293, l='MpServer', x=-266,56, y=4,00, z=42,47], EntitySheep['Sheep'/295, l='MpServer', x=-265,97, y=4,00, z=41,34], EntityTrail['unknown'/32298, l='MpServer', x=-327,87, y=5,62, z=-12,90], EntityBrainyZombie['Angry Zombie'/1216035, l='MpServer', x=-287,50, y=4,00, z=-36,50], EntitySlime['Slime'/426055, l='MpServer', x=-355,38, y=5,00, z=50,63], EntityZombie['Zombie'/1216064, l='MpServer', x=-322,50, y=4,00, z=21,50], EntityItem['item.item.feather'/1217103, l='MpServer', x=-267,47, y=4,13, z=40,97], EntitySpider['Spider'/1294707, l='MpServer', x=-321,38, y=4,00, z=-54,41], EntityItem['item.item.bone'/1151869, l='MpServer', x=-339,03, y=4,13, z=-48,28], EntityZombie['Zombie'/986234, l='MpServer', x=-355,13, y=4,00, z=-33,47], EntitySkeleton['Skeleton'/1294699, l='MpServer', x=-312,50, y=4,00, z=-56,50], EntityItem['item.item.egg'/1172889, l='MpServer', x=-285,53, y=4,13, z=29,50], EntitySkeleton['Skeleton'/1294747, l='MpServer', x=-284,50, y=4,00, z=65,50], EntitySkeleton['Skeleton'/804741, l='MpServer', x=-256,50, y=4,00, z=-34,50], EntitySkeleton['Skeleton'/1294746, l='MpServer', x=-284,50, y=4,00, z=67,50], EntitySlime['Slime'/117643, l='MpServer', x=-352,38, y=4,00, z=48,63], EntitySkeleton['Skeleton'/986242, l='MpServer', x=-345,34, y=4,00, z=-33,78], EntitySkeleton['Skeleton'/986240, l='MpServer', x=-350,44, y=4,00, z=-28,09], EntitySkeleton['Skeleton'/1294748, l='MpServer', x=-289,50, y=4,00, z=65,50], EntitySheep['Sheep'/166, l='MpServer', x=-348,63, y=4,00, z=-79,69], EntityItem['item.item.slimeball'/663200, l='MpServer', x=-335,66, y=4,13, z=-65,44], EntitySheep['Sheep'/186, l='MpServer', x=-328,47, y=4,00, z=-80,13], EntityItem['item.item.feather'/1053613, l='MpServer', x=-264,75, y=4,13, z=46,09], EntitySheep['Sheep'/191, l='MpServer', x=-322,44, y=4,00, z=67,31], EntityPig['Pig'/208, l='MpServer', x=-314,97, y=4,00, z=-89,84], EntitySheep['Sheep'/209, l='MpServer', x=-311,13, y=4,00, z=-83,22], EntityPig['Pig'/210, l='MpServer', x=-309,94, y=4,00, z=-83,13], EntityCreeper['Creeper'/213, l='MpServer', x=-325,03, y=4,00, z=-7,63], EntityCow['Cow'/215, l='MpServer', x=-308,38, y=4,00, z=65,28], EntityPig['Pig'/228, l='MpServer', x=-295,91, y=4,00, z=-85,16], EntityPig['Pig'/229, l='MpServer', x=-290,72, y=4,00, z=-80,31], EntityPig['Pig'/230, l='MpServer', x=-290,78, y=4,00, z=-88,16], EntityPig['Pig'/231, l='MpServer', x=-300,09, y=4,00, z=-74,41], EntitySheep['Sheep'/234, l='MpServer', x=-286,66, y=4,00, z=-0,16], EntityCow['Cow'/235, l='MpServer', x=-291,88, y=4,00, z=37,13], EntityCow['Cow'/236, l='MpServer', x=-297,75, y=4,00, z=57,31], EntitySpider['Spider'/1272319, l='MpServer', x=-271,59, y=4,00, z=55,59], EntitySheep['Sheep'/237, l='MpServer', x=-299,81, y=4,00, z=52,09], EntityCow['Cow'/247, l='MpServer', x=-282,78, y=4,00, z=-47,16], EntitySheep['Sheep'/248, l='MpServer', x=-283,91, y=4,00, z=-41,28], EntityCow['Cow'/249, l='MpServer', x=-283,03, y=4,00, z=-44,91], EntitySkeleton['Skeleton'/1215976, l='MpServer', x=-328,88, y=4,00, z=20,34], EntityPig['Pig'/251, l='MpServer', x=-276,91, y=4,00, z=18,63], EntitySheep['Sheep'/252, l='MpServer', x=-273,88, y=4,00, z=17,72], EntityPig['Pig'/253, l='MpServer', x=-272,66, y=4,00, z=19,72], EntityHorse['Horse'/254, l='MpServer', x=-276,97, y=4,00, z=20,84], EntityHorse['Horse'/255, l='MpServer', x=-279,53, y=4,00, z=17,34]]
    Retry entities: 0 total; []
    Server brand: fml,forge
    Server type: Integrated singleplayer server
Stacktrace:
    at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
    at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2432)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:909)
    at net.minecraft.client.main.Main.main(SourceFile:148)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
    Minecraft Version: 1.7.10
    Operating System: Windows 8.1 (amd64) version 6.3
    Java Version: 1.8.0_40, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 150424032 bytes (143 MB) / 577171456 bytes (550 MB) up to 1060372480 bytes (1011 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP v9.05 FML v7.10.104.1360 Minecraft Forge 10.13.3.1360 30 mods loaded, 30 mods active
    mcp{9.05} [Minecraft Coder Pack](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    FML{7.10.104.1360} [Forge Mod Loader](forge-1.7.10-10.13.3.1360-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Forge{10.13.3.1360} [Minecraft Forge](forge-1.7.10-10.13.3.1360-1.7.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    CodeChickenCore{1.0.2.9} [CodeChicken Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    NotEnoughItems{1.0.2.15} [Not Enough Items](NotEnoughItems-1.7.10-1.0.2.15-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    WitchingGadgetsCore{1.1.6} [Witching Gadgets Core](minecraft.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    jewelrycraft2{1.0.9} [Jewelrycraft 2]([1.7.10] Jewelrycraft2-1.0.9-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    AWWayofTime{v1.3.2} [Blood Magic: Alchemical Wizardry](BloodMagic-1.7.10-1.3.2-1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Baubles{1.0.1.10} [Baubles](Baubles-1.7.10-1.0.1.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Thaumcraft{4.2.3.5} [Thaumcraft](Thaumcraft-1.7.10-4.2.3.5.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Botania{r1.6-187} [Botania](Botania r1.6-187.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    custom_sword{1.7.2} [Custom Sword  By Kelco_K22](custom_sword_1.7.10_V0.10.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    DummyCore{1.11} [DummyCore](DummyCorev1.11.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    essentialcraft{4.5.1710.125} [Essential Craft 3](EssentialCraft3v4.5.1710.131.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    essenthaum{1.1.1710.0} [Essential Thaumaturgy](EssentialThaumaturgy-1.1.1710.11EC%284.4.1710.37%29TC%284.2.3.5%29.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    evilcraft{0.8.6} [EvilCraft](EvilCraft-1.7.10-0.8.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ExtraUtilities{1.2.4b} [Extra Utilities](extrautilities-1.2.4b.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    iChunUtil{4.0.0} [iChunUtil](iChunUtil-4.0.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    IGWMod{1.1.1-17} [In-Game wiki Mod](IGW-Mod-1.7.10-1.1.1-17-universal.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Morph{0.9.1} [Morph](Morph-Beta-0.9.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    swords{1.0} [Mo' Swords Mod](MoSwordsV1.3%281.7.10%29.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThaumicHorizons{1.1.1} [Thaumic Horizons](thaumichorizons-1.7.10-1.1.1.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    thaumicinfusion{4.002} [Thaumic Infusion](ThaumicInfusion-4.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    ThaumicTinkerer{unspecified} [Thaumic Tinkerer](ThaumicTinkerer-2.5-1.7.10-493.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TravellersGear{1.15.7} [Traveller's Gear](TravellersGear-1.7.10-1.15.7.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    TwilightForest{2.3.2} [The Twilight Forest](twilightforest-1.7.10-2.3.2.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    WarpTheory{1.7.10R1.0} [WarpTheory](WarpTheory-1.7-1.0-24.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    witchery{0.24.0} [Witchery](witchery-1.7.10-0.24.0.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    WitchingGadgets{1.1.6} [Witching Gadgets](WitchingGadgets-1.7.10-1.1.6.jar) Unloaded->Constructed->Pre-initialized->Initialized->Post-initialized->Available->Available->Available->Available
    Launched Version: 1.7.10-Forge10.13.3.1360-1.7.10
    LWJGL: 2.9.1
    OpenGL: Intel(R) HD Graphics 4000 GL version 4.0.0 - Build 10.18.10.3308, Intel
    GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

```
Is Modded: Definitely; Client brand changed to 'fml,forge'
Type: Client (map_client.txt)
Resource Packs: []
Current Language: English (US)
Profiler Position: N/A (disabled)
Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
Anisotropic Filtering: Off (1)
```

**Comment by sor1n** [comment]
So this happens only when you open the Liquids tab in the creative inventory? Well I should be able to fix it, but I guess I suggest not going there until the fix (because I'm not sure which mod causes the problem)

**Comment by LiSirNo** [comment]
Well then I am waiting for fix thanks for message
