### ISSUE TITLE
Crash on Server bootup

### ISSUE THREAD

**Issue by Wolfofthenyght** [sor1n/Jewelrycraft#19]
Hey Onyx! I wanted to post this here so that hopefully you can take a look at it. When I updated JC2 on my server to Jewelrycraft2-1.0.10, the server would startup and then crash. The crash report is located here, with information below about what version of forge is running.

http://pastebin.com/AAHqExk8

Forge version 10.13.2.1343-1.7.10-universal.jar

Does this perhaps need an updated version of forge (did you update the fluid handling to the 'fixed' system?), or a dependency that forgot to get mentioned? For now I've simply backdated to JC2 1.0.9 so that it will work, but any info you can provide would be appreciated :) Thanks!

**Comment by sor1n** [comment]
I have fixed the bug in a previous commit, I just never pushed the update. I will do that today.
