### ISSUE TITLE
Error spam packet sent on wrong side.

### ISSUE THREAD

**Issue by rich1051414** [sor1n/Jewelrycraft#23]
EntityHeart Line 78. Packet sent to server within the if statement checking if the code is running server side.
Causes an error to spam the console. I believe the fix would be to break the code out of the side check if you want the player to request an update from the server.

**Comment by sor1n** [comment]
Ok, thanks rich, I will fix this now that I am home.

**Comment by sor1n** [comment]
Ok, I managed to fix this plus a de-sync issue thanks to a friend :)
