### ISSUE TITLE
Feature Request:  Need a way to reposition the heart GUI

### ISSUE THREAD

**Issue by liftoff** [sor1n/Jewelrycraft#24]
Playing CrazyCraft 3.0 which has Mine & Blade Battlegear 2 which places some extra hotbar items on the left and right sides of the screen.  These overlap with the Jewelrycraft 2 heart GUI making the heart stats hard to view.  It would be great if there were a way in the config to move the heart GUI up, down, left, or right by some provided amount of pixels (e.g. like Ingame Info XML).

I looked in the various Jewelrycraft 2 .cfg files and couldn't find anything that would let me reposition the heart GUI.

**Comment by sor1n** [comment]
Gotcha, will add that in the next update (or at least make sure they don't overlap until I add that :p)

**Comment by sor1n** [comment]
Added in version 1.1.0 :)
