### ISSUE TITLE
NEI shading?

### ISSUE THREAD

**Issue by VallenFrostweaver** [sor1n/Jewelrycraft#27]
Not sure if it's NEI or JC2 but when you hover over the tabs of the open JC2 guide book the shading of the blocks as displayed in NEI on the side seems to reverse (ie shading is on top of the blocks you see in NEI)? Not sure here but It's easy enough to reproduce.

**Comment by VallenFrostweaver** [comment]
Forgot to add in screen shot. See attached.
![jc2 shading comparison](https://cloud.githubusercontent.com/assets/13642054/10287059/ef5cdae4-6b88-11e5-9e5c-58411a1e90c8.png)

**Comment by sor1n** [comment]
I know of this, it has to do on how I render things in the book.

**Comment by sor1n** [comment]
Fixed
