### ISSUE TITLE
Storage Displayer font issue

### ISSUE THREAD

**Issue by VallenFrostweaver** [sor1n/Jewelrycraft#28]
Hello,
The Storage Displayer has 2 layers of the font. One in the front and the shadow version in the back. On some items the shadow version defaults to the same color as the front font giving it a "double image" look and difficult to read. I have attached an image.
![jc2 double image](https://cloud.githubusercontent.com/assets/13642054/10286909/1ce88158-6b88-11e5-9e45-67a66a0a5b6d.png)

**Comment by sor1n** [comment]
Does this happen in the latest version (1.1.3) ?

**Comment by VallenFrostweaver** [comment]
Yes. I am currently running 1.1.3.  Be aware that these are only some example items as this does not happen with all items.

**Comment by sor1n** [comment]
Issue has been fixed for the next update
