### ISSUE TITLE
Jewelrycraft guide book minor errors

### ISSUE THREAD

**Issue by VallenFrostweaver** [sor1n/Jewelrycraft#29]
I have written on each image in red to highlight the issues I see. Just letting you know. Not making demands or anything. :)
![jewelry 1](https://cloud.githubusercontent.com/assets/13642054/10308000/e4268916-6c2a-11e5-9177-00e383f73310.png)
![jewelry 2](https://cloud.githubusercontent.com/assets/13642054/10308004/e7657074-6c2a-11e5-9024-d120503c90ef.png)
![jewelry 3](https://cloud.githubusercontent.com/assets/13642054/10308006/ea0bdcb4-6c2a-11e5-98c1-15ff6bdb0066.png)
![oops 1](https://cloud.githubusercontent.com/assets/13642054/10308010/ee53d830-6c2a-11e5-8aa0-f441a437c487.png)
![spelling 1](https://cloud.githubusercontent.com/assets/13642054/10308014/f27ad4c2-6c2a-11e5-9b6d-f16ab5208cfc.png)
![grammar 1](https://cloud.githubusercontent.com/assets/13642054/10308019/f5c0b034-6c2a-11e5-9212-c07623cbef62.png)
![grammar 2](https://cloud.githubusercontent.com/assets/13642054/10308021/f8279b62-6c2a-11e5-834a-e12b59a933c2.png)
![gold](https://cloud.githubusercontent.com/assets/13642054/10308024/fbdf932c-6c2a-11e5-9eda-2ac6ef25d9a6.png)
![challenge](https://cloud.githubusercontent.com/assets/13642054/10308028/fe6488e6-6c2a-11e5-9117-fcea663a9e0a.png)

**Comment by sor1n** [comment]
Thank you, will fix these grammatical errors for the next version :) Also the challenge you can find under the Jewelrycraft achievements page ;)

**Comment by sor1n** [comment]
Done
