### ISSUE TITLE
Rapidly Spinning Items

### ISSUE THREAD

**Issue by NekoBoy4You** [sor1n/Jewelrycraft#34]
Every time I place a item in a molder, smelter ,storage displayer or jeweler's crafting table, the items spin extremely quickly and never stops. I've seen mod reviews of this mod, but their items don't spin. I assume it's a rendering issue, but I'm not so sure. Here's an image:

![2015-10-10_17 31 17](https://cloud.githubusercontent.com/assets/15061122/10409913/b8359818-6f74-11e5-8178-4050fdeb2f3d.png)

![2015-10-10_17 11 54](https://cloud.githubusercontent.com/assets/15061122/10409914/bfffa516-6f74-11e5-9e00-dc7be910a4a1.png)

**Comment by sor1n** [comment]
What version is it? Also does this happen all the time? Does this happen if you put the video settings from fancy to fast? What other mods do you have?

**Comment by NekoBoy4You** [comment]
The mod version is 1.1.3, it happens all the time, they still spin with fast and fancy graphics. My list of mods is rather large. 

JewelryCraft 2
Armorer'sWorkshop
Artifacts
Baubles
Betterfoliage
Biomes'OPlenty
Botania
Carpenter'sBlocks
CoroUtil
CreativeCore
CustomNPC'S
CustomSteve
DamageIndicators
DecoCraft
Mo'Creatures
EnchantingPlus
ExtendedVillages
Flan'sMod
iChunUtil
InfernalMobs
IronChest
ItemPhysics
Llibrary
MalisisCore
MalisisDoors
MCA (MinecraftComesAlive)
MineTradingCards
OpenEye
Optifine
Orespawn
Pam'sHarvestCraft
PlantMegaPack
QuiverBow
RadixCore
ShadersMod
Shincolle
ShipsMod
SuperEnchants
TooManyItems
CuteMobModels
TouhouMod

**Comment by NekoBoy4You** [comment]
Wait, hold on, I got rid of ItemPhysics and it's all fine and dandy. Sorry for wasting your time. Maybe you could fix this in a future update?

![2015-10-11_13 37 50](https://cloud.githubusercontent.com/assets/15061122/10414535/539af746-701d-11e5-975b-d8c2a56d9155.png)

**Comment by sor1n** [comment]
I will, but I need to find out what does ItemPhysics change, but until then I will leave this open.

**Comment by sor1n** [comment]
I have decided not to bother with this bug
