### ISSUE TITLE
Gradle buildfiles are absent from 1.7.10/master branches

### ISSUE THREAD

**Issue by Laikulo** [sor1n/Jewelrycraft#5]
There are no gradle buildfiles in the master branch, or the 1,7,10 branch, therefore, when gradle tries to build them, it just plain won't work.

**Comment by Laikulo** [comment]
Obligatory-but-pointless buildlog: http://ci.jam-craft.net/job/JewelryCraft/branch/1.7.10/1/console

**Comment by sor1n** [comment]
It should work now
