### ISSUE TITLE
Crash with ExtraUtilities and Microblocks

### ISSUE THREAD

**Issue by medsal15** [sor1n/Jewelrycraft#7]
http://pastebin.com/wny2s2xU

100% sure it's Jeweltycraft but I'm gonna try without to see if I'm right.

**Comment by medsal15** [comment]
Confirmed. I launched minecraft without Jewelrycraft without crashing.

**Comment by sor1n** [comment]
I will look into fixing it asap.

**Comment by sor1n** [comment]
Fixed the issue. Things should work just fine in the next version, which should be out soon (need to wait for Jenkins to generate the build)
