### ISSUE TITLE
Conflict still exists with Fossils and Archeology mod.

### ISSUE THREAD

**Issue by CrazedKitty1290** [sor1n/Jewelrycraft#8]
http://pastebin.com/s8LSxi2r

Here's the full report encase you might need it. It still crashes on start up.

**Comment by sor1n** [comment]
Ok, yeah, I know it is crashing, I even looking in their code. The way they coded - works for them, not for what I am doing. I can do something which will totally work, but it would mean that the mod's items won't display in the jewelry modifier GUI. You can still add them normally through the ritual. Would that be a problem if I did that?

**Comment by CrazedKitty1290** [comment]
I wouldn't mind it. I'm thinking about getting rid of the fossils mod because I already have JurrasiCraft, which works just fine with Jewelrycraft just fine. I can also message them to see if they can make it more compatible with your mod too.

**Comment by sor1n** [comment]
I will still try to fix this issue. Because a lot of mods are doing stupid things (not to insult them) and make my mod look like the bad guy here XD

**Comment by CrazedKitty1290** [comment]
Okay then. Let's see what happens then, hm?

**Comment by sor1n** [comment]
I managed to fix the issue. Next version that comes out will have the fix :)
